package com.example.transactionstarter.service;

import java.util.List;
import java.util.UUID;

import org.springframework.stereotype.Service;

import com.example.transactionstarter.dto.TransactionRequest;
import com.example.transactionstarter.exception.InvalidTransactionStatusException;
import com.example.transactionstarter.exception.TransactionNotFoundException;
import com.example.transactionstarter.model.Transaction;
import com.example.transactionstarter.model.TransactionStatus;
import com.example.transactionstarter.repository.TransactionRepository;

@Service
public class TransactionService {

    private final TransactionRepository transactionRepository;

    public TransactionService(TransactionRepository transactionRepository) {
        this.transactionRepository = transactionRepository;
    }

    // A. Create transaction

    public Transaction createTransaction(
            TransactionRequest request,
            String idempotencyKey) {

        if (transactionRepository.findByIdempotencyKey(idempotencyKey).isPresent()) {

            return transactionRepository
                    .findByIdempotencyKey(idempotencyKey)
                    .get();
        }

        Transaction transaction = new Transaction();

        // Transaction ID is generated by the server
        transaction.setTransactionId(UUID.randomUUID().toString());

        transaction.setIdempotencyKey(idempotencyKey);
        transaction.setCustomerId(request.getCustomerId());
        transaction.setAmount(request.getAmount());
        transaction.setCurrency(request.getCurrency().toUpperCase());
        transaction.setTransactionType(request.getTransactionType());

        // Every newly created transaction starts as PENDING
        transaction.setTransactionStatus(TransactionStatus.PENDING);

        return transactionRepository.save(transaction);
    }


    // B. Get transaction by Transaction ID

    public Transaction getTransaction(String transactionId) {

        return transactionRepository.findById(transactionId)
                .orElseThrow(() ->
                        new TransactionNotFoundException(
                                "Transaction not found: " + transactionId));
    }


    // C. Update transaction status

    public Transaction updateTransactionStatus(
            String transactionId,
            TransactionStatus newStatus) {

        Transaction transaction = transactionRepository
                .findById(transactionId)
                .orElseThrow(() ->
                        new TransactionNotFoundException(
                                "Transaction not found: " + transactionId));

        TransactionStatus currentStatus =
                transaction.getTransactionStatus();

        /*
         * Only PENDING transactions can change status.
         *
         * Allowed:
         * PENDING -> COMPLETED
         * PENDING -> FAILED
         * PENDING -> CANCELLED
         */

        if (currentStatus == TransactionStatus.PENDING
                && (newStatus == TransactionStatus.COMPLETED
                || newStatus == TransactionStatus.FAILED
                || newStatus == TransactionStatus.CANCELLED)) {

            transaction.setTransactionStatus(newStatus);

            return transactionRepository.save(transaction);
        }

        throw new InvalidTransactionStatusException(
                "Cannot change transaction status from "
                        + currentStatus
                        + " to "
                        + newStatus);
    }


    // D. Get all transactions for a Customer ID

    public List<Transaction> getCustomerTransactions(String customerId) {

        return transactionRepository.findByCustomerId(customerId);
    }
}